version: '3.7'
services:
  mongoservice:
    image: mongo
    container_name: myMongoDB
    environment:
      - MONGO_INITDB_DATABASE=test_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017

  perdimisdocumentos_api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_HOST=mongoservice
      - WAIT_FOR_DB=mongoservice:27017
    depends_on:
      - mongoservice
    ports:
      - 8080:8080





